name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run Prettier Check
        run: npm run format:check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: npm run build
